namespace: helm3
config:
  guestbook_name: "MyPopRock Festival 2.0"
  backend_uri: "http://helmbe.ibera.fun/guestbook"
replicaCount: 1
image:
  repository: phico/frontend
  tag: "2.0"
service:
  port: 80
  type: LoadBalancer
ingress:
  host: helmfe.ibera.fun