apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  namespace: helm3
  name: guestbook-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: helmfe.ibera.fun
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: frontend
            port: 
              number: 80